### ISSUE TITLE
Error: bootstrap-3.8.0.chromium.8_bin/python3/bin/python3: No such file or directory - while building meta-flutter for yocto project

### ISSUE THREAD

**Issue by sathishkumar458** [sony/meta-flutter#17]
Creating Flutter engine for Linux target machine (qemuarm64)

Followed steps as mentioned in the below link (i.e Meta-flutter Yocto Project)

https://github.com/sony/meta-flutter

1. Building Yocto - Followed all steps as mentioned
2. Cross-building using bitbake -
    i. Wayland backend -  
        a. bitbake flutter-wayland-client   -- while making bitbake of Flutter engine getting below errors,

Error:
Error: failed to update packages, see the log.
/home/user/FlutterPort/build/tmp/work/aarch64-poky-linux/flutter-engine/1.0-r0/git/bootstrap_python3: line 32: bootstrap-3.8.0.chromium.8_bin/python3/bin/python3: No such file or directory
cat: /home/user/FlutterPort/build/tmp/work/aarch64-poky-linux/flutter-engine/1.0-r0/git/python3_bin_reldir.txt: No such file or directory
/home/user/FlutterPort/build/tmp/work/aarch64-poky-linux/flutter-engine/1.0-r0/git/vpython3: line 52: /home/user/FlutterPort/build/tmp/work/aarch64-poky-linux/flutter-engine/1.0-r0/git/.cipd_bin/vpython3: No such file or directory
WARNING: exit code 127 from a shell command.

Tried Below Solutions:
1. Set the environment variable DEPOT_TOOLS_UPDATE=0.
2. Downloaded "DEPOT TOOLS"  from below link and set the path
   i. git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
  ii. export PATH=/path/to/depot_tools:$PATH
3. Removed other version Python's 

Could anyone please help/support to proceed further.

**Comment by HidenoriMatsubayashi** [comment]
First of all, I would like to ask you, are you using the recipe file as it is or are you customizing it?

> Tried Below Solutions:

We have already done the same thing in https://github.com/sony/meta-flutter/blob/main/recipes-graphics/flutter-engine/flutter-engine.bb#L37

**Comment by sathishkumar458** [comment]
Hi Mr. Hidenori Mastubayashi,
Thank you very much for your reply..
iam using same recipe file with any customization.

**Comment by HidenoriMatsubayashi** [comment]
Unfortunately, I have no idea to fsolve this issue at this time, but could you try https://github.com/sony/flutter-embedded-linux/wiki/Building-Flutter-Engine-from-source#python-2?

**Comment by jwinarske** [comment]
@sathishkumar458 You might consider using https://github.com/meta-flutter/meta-flutter

**Comment by HidenoriMatsubayashi** [comment]
memo for my work.

```
| ________ running 'python3 src/tools/remove_stale_pyc_files.py src/tools' in '/home/hidenori/workspace/flutter/yocto/build/tmp/work/aarch64-poky-linux/flutter-engine/1.0-r0'
| ________ running 'python3 src/build/linux/sysroot_scripts/install-sysroot.py --arch=x64' in '/home/hidenori/workspace/flutter/yocto/build/tmp/work/aarch64-poky-linux/flutter-engine/1.0-r0'
| Installing Debian sid amd64 root image: /home/hidenori/workspace/flutter/yocto/build/tmp/work/aarch64-poky-linux/flutter-engine/1.0-r0/src/build/linux/debian_sid_amd64-sysroot
| Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/79a7783607a69b6f439add567eb6fcb48877085c/debian_sid_amd64_sysroot.tar.xz
| Hook 'python3 src/build/linux/sysroot_scripts/install-sysroot.py --arch=x64' took 31.97 secs
| ________ running 'python3 src/build/linux/sysroot_scripts/install-sysroot.py --arch=arm64' in '/home/hidenori/workspace/flutter/yocto/build/tmp/work/aarch64-poky-linux/flutter-engine/1.0-r0'
| Installing Debian sid arm64 root image: /home/hidenori/workspace/flutter/yocto/build/tmp/work/aarch64-poky-linux/flutter-engine/1.0-r0/src/build/linux/debian_sid_arm64-sysroot
| Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/2cade9ee1ca9186b28ac768c19e1ab7c45ee0600/debian_sid_arm64_sysroot.tar.xz
| Hook 'python3 src/build/linux/sysroot_scripts/install-sysroot.py --arch=arm64' took 18.03 secs
| ________ running 'python3 src/flutter/tools/pub_get_offline.py' in '/home/hidenori/workspace/flutter/yocto/build/tmp/work/aarch64-poky-linux/flutter-engine/1.0-r0'
| Hook 'python3 src/flutter/tools/pub_get_offline.py' took 50.50 secs
| ________ running 'python3 src/flutter/tools/download_dart_sdk.py --fail-loudly' in '/home/hidenori/workspace/flutter/yocto/build/tmp/work/aarch64-poky-linux/flutter-engine/1.0-r0'
| multiprocessing.pool.RemoteTraceback:
| """
| Traceback (most recent call last):
|   File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
|     result = (True, func(*args, **kwds))
|   File "src/flutter/tools/download_dart_sdk.py", line 195, in DownloadAndExtract
|     archive = DownloadDartSDK(channel, version, os_name, arch, verbose)
|   File "src/flutter/tools/download_dart_sdk.py", line 112, in DownloadDartSDK
|     curl_result = subprocess.run(
|   File "/usr/lib/python3.8/subprocess.py", line 493, in run
|     with Popen(*popenargs, **kwargs) as process:
|   File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
|     self._execute_child(args, executable, preexec_fn, close_fds,
|   File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
|     raise child_exception_type(errno_num, err_msg, err_filename)
| FileNotFoundError: [Errno 2] No such file or directory: 'curl'
| """
| 
| The above exception was the direct cause of the following exception:
| 
| Traceback (most recent call last):
|   File "src/flutter/tools/download_dart_sdk.py", line 293, in <module>
|     sys.exit(Main())
|   File "src/flutter/tools/download_dart_sdk.py", line 286, in Main
|     result = async_result.get()
|   File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
|     raise self._value
| FileNotFoundError: [Errno 2] No such file or directory: 'curl'
| WARNING: Your metrics.cfg file was invalid or nonexistent. A new one will be created.
| Error: Command 'python3 src/flutter/tools/download_dart_sdk.py --fail-loudly' returned non-zero exit status 1 in /home/hidenori/workspace/flutter/yocto/build/tmp/work/aarch64-poky-linux/flutter-engine/1.0-r0
| Hook 'python3 src/flutter/tools/download_dart_sdk.py --fail-loudly' took 13.18 secs
| WARNING: exit code 2 from a shell command.
| ERROR: Execution of '/home/hidenori/workspace/flutter/yocto/build/tmp/work/aarch64-poky-linux/flutter-engine/1.0-r0/temp/run.do_configure.1489702' failed with exit code 2
ERROR: Task (/home/hidenori/workspace/flutter/yocto/meta-flutter/recipes-graphics/flutter-engine/flutter-engine.bb:do_configure) failed with exit code '1'
```
